AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/aws-sam-helloworlds3-1.0.jar
      Handler: com.harprit.aws.sam.helloworlds3.App::handleRequest
      Runtime: java8
      Timeout: 300
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref MyTable
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: MyBucket
            Events:
            - s3:ObjectCreated:*
  MyBucket:
    Type: AWS::S3::Bucket
  
  MyTable:
    Type: AWS::Serverless::SimpleTable
    
Outputs:
  MyBucketName:
    Value: !Ref MyBucket
  MyTableName:
    Value: !Ref MyTable